const errorHandler = async (err, req, res, next) => {
  console.log(err);
};
